$apiUrl = "http://localhost:8080/api/cdws"
$missionId = "451fad2e-99ba-4d5a-af10-037f1adf913d"

# Test 1: POST avec CD/W No. valide
Write-Host "==== TEST 1: CREATE CDW WITH VALID CD/W No. ====" -ForegroundColor Green

$validPayload = @{
    "CD/W No." = "CDW-001"
    "Description" = "Test CDW with valid number"
    "Final Conclusion on Severity" = "Deficiency in Internal Control"
    "FSLI" = "Information generated by an IT application"
    "Internal Control Component" = "ITGC"
    "Business Process" = "Information Technology General Controls"
    "Audit Unit" = "OrionBank 2024-HQ"
    "Exception Identified By" = "AuditNova"
    "Assertions" = "C,A,CO,E/O,R&O,P&D,V"
    "Audit Response" = "Test response"
    "Does the deficiency relate directly to the achievement of one or more financial statement assertions?" = $false
    "Is the likelihood of a misstatement resulting from the deficiency/weakness (or combination) at least reasonably possible?" = $false
    "Value of transactions or accounts exposed or expected to be exposed to the deficiency/weakness - Interim" = 0
    "Value of transactions or accounts exposed or expected to be exposed to the deficiency/weakness - Annual" = 0
    "Is the magnitude of the potential misstatement, which is at least reasonably possible (considering quantitative and qualitative factors), material to either the interim or annual financial statements?" = $false
    "Factors considered in determining likelihood and magnitude" = "No direct impact"
    "Is this at least a significant deficiency?" = $false
    "Rationale" = "Test rationale"
    "Do compensating controls exist and operate effectively, at a level of precision sufficient to prevent or detect a misstatement that could be material to either interim or annual financial statements?" = $false
    "Description of Compensating Controls" = ""
    "Refer to where testing (either by us or management) of compensating control was documented in the work-papers" = ""
    "Is this a Material Weakness?" = $false
    "Document Rationale" = ""
    "Are there multiple control deficiencies and/or significant deficiencies that affect the same financial statement account balance or disclosure?" = $false
    "Aggregation Description" = "Test aggregation"
    "Source Ref. No." = "REF-001"
    "Title" = "Test Title"
    "Sub-process" = "Test Sub-process"
    "FSLI or Disclosure" = ""
    "Roll Forward?" = $false
    "Control No." = "1350"
    "Control Title" = "Test Control"
    "Audit Response Links" = ""
    "Aggregation Reference" = ""
    "IsReportedToManagement" = $false
    "ExceptionAmount" = 0
    "AffectedPopulationAmount" = 0
    "RootCause" = "Test root cause"
    "Implication" = "Test implication"
    "Recommendation" = "Test recommendation"
    "ResponsiblePerson" = "Test Person"
    "TargetDate" = "2026-06-30"
} | ConvertTo-Json

try {
    $response = Invoke-WebRequest -Uri "$apiUrl/$missionId" `
        -Method POST `
        -ContentType "application/json" `
        -Body $validPayload `
        -ErrorAction Stop
    
    Write-Host "✓ SUCCESS: CDW created successfully" -ForegroundColor Green
    Write-Host "Response: " $response.StatusCode
    $response.Content | ConvertFrom-Json | ConvertTo-Json | Write-Host
} catch {
    Write-Host "✗ FAILED: " $_.Exception.Message -ForegroundColor Red
    if ($_.Exception.Response.StatusCode) {
        Write-Host "Status Code: " $_.Exception.Response.StatusCode
    }
}

Write-Host ""
Write-Host "==== TEST 2: CREATE CDW WITHOUT CD/W No. (SHOULD FAIL) ====" -ForegroundColor Yellow

$invalidPayload = @{
    "Description" = "Test CDW without number"
    "Final Conclusion on Severity" = "Deficiency"
} | ConvertTo-Json

try {
    $response = Invoke-WebRequest -Uri "$apiUrl/$missionId" `
        -Method POST `
        -ContentType "application/json" `
        -Body $invalidPayload `
        -ErrorAction Stop
    
    Write-Host "✗ UNEXPECTED: Should have failed but succeeded" -ForegroundColor Red
} catch {
    if ($_.Exception.Response.StatusCode -eq 400) {
        Write-Host "✓ SUCCESS: Correctly rejected invalid request (400 Bad Request)" -ForegroundColor Green
        try {
            $errorResponse = $_.Exception.Response.GetResponseStream()
            $reader = New-Object System.IO.StreamReader($errorResponse)
            $errorContent = $reader.ReadToEnd()
            Write-Host "Error Response: " -ForegroundColor Cyan
            $errorContent | ConvertFrom-Json | ConvertTo-Json | Write-Host
        } catch {
            Write-Host "Error Response: " $_.Exception.Message -ForegroundColor Cyan
        }
    } else {
        Write-Host "✗ FAILED with unexpected status code: " $_.Exception.Response.StatusCode -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "==== SUMMARY ====" -ForegroundColor Cyan
Write-Host "Test 1: POST avec CD/W No. valide - Devrait RÉUSSIR"
Write-Host "Test 2: POST sans CD/W No. - Devrait ÉCHOUER avec 400"
