# Script complet pour tester l'endpoint POST CDW

# Configuration
$apiUrl = "http://localhost:8080/api/cdws"
$missionId = "451fad2e-99ba-4d5a-af10-037f1adf913d"

# JSON complet à poster
$cdwData = @{
    "CD/W No." = "CDW-001"
    "Description" = "We have identified 2 profiles on Atlas that enable holders to make and approve recycling operations (correction of flows in the event of rejection or anomaly). In addition, we noted the presence of 243 accounts with these profiles and therefore incompatible rights."
    "Remediated as of, or prior to period-end?" = $false
    "Final Conclusion on Severity" = "Deficiency in Internal Control"
    "FSLI" = "Information generated by an IT application"
    "Internal Control Component" = "ITGC"
    "Business Process" = "Information Technology General Controls"
    "Audit Unit" = "OrionBank 2024-HQ"
    "Exception Identified By" = "AuditNova"
    "Assertions" = "C,A,CO,E/O,R&O,P&D,V"
    "Audit Response" = "AuditNova Lyon performed an independent analysis of all manual journal entries to confirm that all users with conflicting rights did not make or approve any manual journal entries during 2024."
    "Does the deficiency relate directly to the achievement of one or more financial statement assertions?" = $false
    "Is the likelihood of a misstatement resulting from the deficiency/weakness (or combination) at least reasonably possible?" = $false
    "Value of transactions or accounts exposed or expected to be exposed to the deficiency/weakness - Interim" = 0
    "Value of transactions or accounts exposed or expected to be exposed to the deficiency/weakness - Annual" = 0
    "Is the magnitude of the potential misstatement, which is at least reasonably possible (considering quantitative and qualitative factors), material to either the interim or annual financial statements?" = $false
    "Factors considered in determining likelihood and magnitude" = "No direct financial statement impact identified based on the procedures performed."
    "Is this at least a significant deficiency?" = $false
    "Rationale" = "No significant deficiency concluded based on the audit response and absence of identified inappropriate journal activity."
    "Do compensating controls exist and operate effectively, at a level of precision sufficient to prevent or detect a misstatement that could be material to either interim or annual financial statements?" = $false
    "Description of Compensating Controls" = ""
    "Refer to where testing (either by us or management) of compensating control was documented in the work-papers" = ""
    "Is this a Material Weakness?" = $false
    "Document Rationale" = ""
    "Are there multiple control deficiencies and/or significant deficiencies that affect the same financial statement account balance or disclosure?" = $false
    "Aggregation Description" = "Users can both enter and validate recycling and correction operations in the event of rejection of Lumina data."
    "Source Ref. No." = ""
    "Title" = "IT process-wide considerations"
    "Sub-process" = "IT process-wide considerations"
    "FSLI or Disclosure" = ""
    "Roll Forward?" = $false
    "Control No." = "1350"
    "Control Title" = "Information generated by an IT application may not be reliable"
    "Audit Response Links" = ""
    "Aggregation Reference" = ""
    "IsReportedToManagement" = $false
    "ExceptionAmount" = 0
    "AffectedPopulationAmount" = 0
    "RootCause" = "Incompatible rights assigned to profiles allowing entry and approval of recycling operations."
    "Implication" = "Potential risk that information generated by the application may not be reliable."
    "Recommendation" = "Review and remove conflicting access rights and strengthen segregation of duties for recycling operations."
    "ResponsiblePerson" = "AuditNova"
    "TargetDate" = "2026-06-30"
} | ConvertTo-Json

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "TEST CDW POST ENDPOINT" -ForegroundColor Green
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "📋 Configuration:" -ForegroundColor Yellow
Write-Host "  Endpoint: POST $apiUrl/$missionId" -ForegroundColor White
Write-Host "  Mission ID: $missionId" -ForegroundColor White
Write-Host "  CD/W No.: CDW-001" -ForegroundColor White
Write-Host ""

Write-Host "📤 Envoi de la requête..." -ForegroundColor Yellow

try {
    $response = Invoke-WebRequest -Uri "$apiUrl/$missionId" `
        -Method POST `
        -ContentType "application/json" `
        -Body $cdwData `
        -ErrorAction Stop

    Write-Host "✅ SUCCÈS! Réponse reçue" -ForegroundColor Green
    Write-Host ""
    Write-Host "📊 Status Code: $($response.StatusCode)" -ForegroundColor Green
    Write-Host ""

    $responseData = $response.Content | ConvertFrom-Json

    Write-Host "📝 Réponse détaillée:" -ForegroundColor Cyan
    Write-Host "  Success: $($responseData.success)" -ForegroundColor White
    Write-Host "  Message: $($responseData.message)" -ForegroundColor White
    Write-Host ""

    if ($responseData.data) {
        Write-Host "📦 Données créées:" -ForegroundColor Cyan
        Write-Host "  ID: $($responseData.data.id)" -ForegroundColor White
        Write-Host "  Mission ID: $($responseData.data.missionId)" -ForegroundColor White
        Write-Host "  CD/W No.: $($responseData.data.cdwNo)" -ForegroundColor White
        Write-Host "  Title: $($responseData.data.title)" -ForegroundColor White
        Write-Host "  Description: $($responseData.data.description.Substring(0, [Math]::Min(50, $responseData.data.description.Length)))..." -ForegroundColor White
        Write-Host "  Severity: $($responseData.data.finalConclusionOnSeverity)" -ForegroundColor White
        Write-Host "  Audit Unit: $($responseData.data.auditUnit)" -ForegroundColor White
        Write-Host "  Created By: $($responseData.data.createdBy)" -ForegroundColor White
        Write-Host "  Created Date: $($responseData.data.createdDate)" -ForegroundColor White
    }

    Write-Host ""
    Write-Host "======================================" -ForegroundColor Cyan
    Write-Host "✅ TEST PASSED - CDW créé avec succès!" -ForegroundColor Green
    Write-Host "======================================" -ForegroundColor Cyan

} catch {
    Write-Host "❌ ERREUR!" -ForegroundColor Red
    Write-Host ""

    if ($_.Exception.Response) {
        Write-Host "📊 Status Code: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
        Write-Host "Status Description: $($_.Exception.Response.StatusDescription)" -ForegroundColor Red
        Write-Host ""

        try {
            $errorStream = $_.Exception.Response.GetResponseStream()
            $reader = New-Object System.IO.StreamReader($errorStream)
            $errorContent = $reader.ReadToEnd()
            $reader.Close()

            $errorData = $errorContent | ConvertFrom-Json

            Write-Host "📋 Détails de l'erreur:" -ForegroundColor Yellow
            Write-Host "  Success: $($errorData.success)" -ForegroundColor White
            Write-Host "  Message: $($errorData.message)" -ForegroundColor White

            if ($errorData.data) {
                Write-Host "  Data: $($errorData.data | ConvertTo-Json)" -ForegroundColor White
            }
        } catch {
            Write-Host "Erreur brut: $errorContent" -ForegroundColor White
        }
    } else {
        Write-Host "Erreur: $($_.Exception.Message)" -ForegroundColor Red
    }

    Write-Host ""
    Write-Host "======================================" -ForegroundColor Cyan
    Write-Host "❌ TEST FAILED" -ForegroundColor Red
    Write-Host "======================================" -ForegroundColor Cyan
}

Write-Host ""
Write-Host "🔍 Conseils de dépannage:" -ForegroundColor Cyan
Write-Host "  1. Vérifier que l'application démarre: http://localhost:8080" -ForegroundColor White
Write-Host "  2. Vérifier que MongoDB a été nettoyé" -ForegroundColor White
Write-Host "  3. Vérifier les logs de l'application" -ForegroundColor White
Write-Host ""

