# CDW Report Generation - PowerShell Test Script
# Usage: .\test-cdw-report.ps1 -FilePath "path\to\file.xlsx" -ProjectId "proj-001" -GeneratedBy "user@example.com"

param (
    [Parameter(Mandatory=$true)]
    [string]$FilePath,

    [Parameter(Mandatory=$true)]
    [string]$ProjectId,

    [Parameter(Mandatory=$true)]
    [string]$GeneratedBy,

    [Parameter(Mandatory=$false)]
    [string]$BaseUrl = "http://localhost:8080"
)

# Validation du fichier
if (-not (Test-Path $FilePath)) {
    Write-Error "File not found: $FilePath"
    exit 1
}

$file = Get-Item -Path $FilePath
$fileName = $file.Name

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "CDW Report Generation Test" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "File: $FilePath" -ForegroundColor Green
Write-Host "Project ID: $ProjectId" -ForegroundColor Green
Write-Host "Generated By: $GeneratedBy" -ForegroundColor Green
Write-Host "Base URL: $BaseUrl" -ForegroundColor Green
Write-Host ""

$url = "$BaseUrl/api/cdw-reports/generate-from-upload"

try {
    Write-Host "Sending request to: $url" -ForegroundColor Yellow
    Write-Host "Waiting for response..." -ForegroundColor Yellow

    $form = @{
        file = $file
        projectId = $ProjectId
        generatedBy = $GeneratedBy
    }

    $response = Invoke-WebRequest -Uri $url `
        -Method Post `
        -Form $form `
        -ContentType "multipart/form-data" `
        -TimeoutSec 600

    Write-Host ""
    Write-Host "========== SUCCESS ==========" -ForegroundColor Green
    Write-Host "Status Code: $($response.StatusCode)" -ForegroundColor Green
    Write-Host ""

    $content = $response.Content | ConvertFrom-Json

    Write-Host "Response Details:" -ForegroundColor Cyan
    Write-Host "  Report ID: $($content.reportId)" -ForegroundColor White
    Write-Host "  Generation Run ID: $($content.generationRunId)" -ForegroundColor White
    Write-Host "  Status: $($content.status)" -ForegroundColor White
    Write-Host "  File Name: $($content.fileName)" -ForegroundColor White
    Write-Host "  Message: $($content.message)" -ForegroundColor White
    Write-Host ""
    Write-Host "Download URL:" -ForegroundColor Yellow
    Write-Host "  $($content.downloadUrl)" -ForegroundColor White
    Write-Host ""

} catch {
    Write-Host ""
    Write-Host "========== ERROR ==========" -ForegroundColor Red
    Write-Host "Status Code: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
    Write-Host "Error Message: $($_.Exception.Message)" -ForegroundColor Red

    if ($_.Exception.Response.StatusCode -eq "BadRequest") {
        Write-Host ""
        Write-Host "Possible causes:" -ForegroundColor Yellow
        Write-Host "  - File is not a valid Excel file (.xlsx or .xls)" -ForegroundColor White
        Write-Host "  - File is corrupted" -ForegroundColor White
        Write-Host "  - File is empty" -ForegroundColor White
    }

    if ($_.Exception.Response.StatusCode -eq "InternalServerError") {
        Write-Host ""
        Write-Host "Possible causes:" -ForegroundColor Yellow
        Write-Host "  - FastAPI service is not running" -ForegroundColor White
        Write-Host "  - Azure Blob Storage connection is invalid" -ForegroundColor White
        Write-Host "  - MongoDB connection is invalid" -ForegroundColor White
        Write-Host "  - Check app.log for more details" -ForegroundColor White
    }

    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Test completed successfully!" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

