package com.pwc.auditit.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for successful Entra ID authentication response.
 * Returned by the backend after successful login via Entra ID.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EntraAuthResponseDto {

    /**
     * JWT token generated by the backend for authenticated session.
     */
    private String token;

    /**
     * Authenticated user information.
     */
    private AuthResponse.UserInfo user;

    /**
     * Frontend redirect URL after successful authentication.
     */
    private String redirectUrl;

    /**
     * Message describing the authentication result.
     */
    private String message;
}

